<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-02-01T18:28:41 CST" name="Default suite" finished-at="2020-02-01T18:29:17 CST" duration-ms="35666">
    <groups>
    </groups>
    <test started-at="2020-02-01T18:28:41 CST" name="Default test" finished-at="2020-02-01T18:29:17 CST" duration-ms="35666">
      <class name="testcases.AccountPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:testcases.AccountPageTest@49139829]" started-at="2020-02-01T18:28:42 CST" name="setup" finished-at="2020-02-01T18:28:53 CST" duration-ms="11127" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="createAccountTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:testcases.AccountPageTest@49139829]" started-at="2020-02-01T18:28:53 CST" name="createAccountTest" data-provider="getAccountData" finished-at="2020-02-01T18:29:15 CST" duration-ms="22609" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[TC-1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[userone userone]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[2134567897']]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[userotester@mail.com]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Test1234@]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at base.CommonMethods.isDisplayed(CommonMethods.java:49)
at pages.AccountPage.accountSuccessful(AccountPage.java:45)
at testcases.AccountPageTest.createAccountTest(AccountPageTest.java:31)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccountTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:testcases.AccountPageTest@49139829]" started-at="2020-02-01T18:29:15 CST" name="tearDown" finished-at="2020-02-01T18:29:17 CST" duration-ms="1466" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createAccountTest status=FAILURE method=AccountPageTest.createAccountTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:testcases.AccountPageTest@49139829] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.AccountPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
